name: iotagent-java

# Triggered after a branch is created, a tag or a branch is pushed or a PR
on:
  create:
  push:
  pull_request:

jobs:

  python-tests:
    name: Build and Tests
    if: contains(github.event.head_commit.message, 'ci skip') == false # if the commit message has ci skip, doesn't run anything because needs
    runs-on: ubuntu-18.04
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '8'
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots verify
    - name: Run test
      run: mvn test